name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
     
      - name: Checkout repo
        uses: actions/checkout@v4
      
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      
      - name: Debug Directory Structure
        run: |
          echo "Current working directory: $(pwd)"
          echo "Root contents:"
          ls -la
          echo "Finding pom.xml files:"
          find . -name "pom.xml" -type f
      
      
      - name: Build Maven Project
        working-directory: backend
        run: |
          echo "Maven working directory: $(pwd)"
          ls -la
          mvn clean package -DskipTests
      
     
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      
      - name: Build Docker Image
        working-directory: backend
        run: |
          echo "Docker build directory: $(pwd)"
          ls -la
          docker build -t guidance-app:latest .
      
      
      - name: Push Docker Image
        run: |
          docker tag vibewrite-app:latest ${{ secrets.DOCKER_USERNAME }}/vibewrite-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/vibewrite-app:latest


     
